resource "azurerm_resource_group" "infra_rg" {
  name     = "platform-infra-rg"
  location = "westeurope"

  tags = {
    RGOwner = "Platform"
  }
}

resource "azurerm_storage_account" "web_storage" {
  name                     = "dmpltfwebsiteapp2026" # Must be globally unique, lowercase alphanumeric only
  resource_group_name      = azurerm_resource_group.infra_rg.name
  location                 = azurerm_resource_group.infra_rg.location
  account_tier             = "Standard"
  account_replication_type = "LRS"

  static_website {
    index_document = "index.html"
  }
}

resource "azurerm_storage_blob" "index_html" {
  name                   = "index.html"
  storage_account_name   = azurerm_storage_account.web_storage.name
  storage_container_name = "$web" # This special container is automatically generated by static_website
  type                   = "Block"
  content_type           = "text/html"

  # Generates the file content dynamically inline using your variable
  content = <<EOF
<!DOCTYPE html>
<html>
<head>
    <title>Deployed via Terraform</title>
</head>
<body>
    <h1>Deployment Successful!</h1>
    <p><strong>Commit ID:</strong> ${var.commit_id}</p>
</body>
</html>
EOF
}
