name: Trigger App Deployment

on:
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:

      - name: Trigger application deployment
        env:
          GH_TOKEN: ${{ secrets.GH_PLATFORM_SECRET }}
        run: |
          HTTP_CODE=$(curl \
            -s \
            -o /dev/null \
            -w "%{http_code}" \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            https://api.github.com/repos/MakovecOrg/platform-demo-app/dispatches \
            -d '{"event_type":"deploy"}'

          echo "Response: $HTTP_CODE"
